# action.yml
name: "pypiinthesky"
description: "Versioning action for pypi packages"
branding:
  icon: "thumbs-up"
  color: "white"
inputs:
  package_name:
    description: "Name of your pypi package. It can either exist, or be created anew, so long as you own the name."
    required: true
  pypi_email:
    description: "Your pypi email."
    required: true
  pypi_password:
    description: "Your pypi password."
    required: true
  bump_type:
    description: "The semver bump to apply: `major`, `minor`, `patch`."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.package_name }}
    - ${{ inputs.pypi_email }}
    - ${{ inputs.pypi_password }}
    - ${{ github.actor }}
    - ${{ inputs.bump_type }}
