# action.yml
name: "pypiinthesky"
description: "Versioning action for pypi packages"
branding:
  icon: "thumbs-up"
  color: "white"
inputs:
  package_name:
    description: "Name of your pypi package. It can either exist, or be created anew, so long as you own the name."
    required: true
  pypi_email:
    description: "Your pypi email."
    required: true
  pypi_password:
    description: "Your pypi password."
    required: true
  gh_username:
    description: "Your github username."
    required: true
  gh_email:
    description: "Your github email."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.package_name }}
    - ${{ inputs.pypi_email }}
    - ${{ inputs.pypi_password }}
    - ${{ inputs.gh_username }}
    - ${{ inputs.gh_email }}
